---
name: 'PR Tests of the install_build_artifact task'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-install-build-artifact-task-on-ubuntu:
    strategy:
      matrix:
        os-version:
          - 22.04
          - 24.04
    runs-on: ${{ format('ubuntu-{0}', matrix.os-version) }}
    steps:
      - uses: actions/checkout@v4
      - id: install-bolt
        uses: ./.github/actions/bolt
        with:
          os-version: ${{ matrix.os-version }}
      - name: Run openvox-agent install task
        run: bolt task run openvox_bootstrap::install_build_artifact version=8.15.0 --targets localhost --run-as root
      - name: Verify openvox-agent is installed
        run: bolt task run openvox_bootstrap::check version=8.15.0 --targets localhost --run-as root
      - name: Verify idempotency
        run: bolt task run openvox_bootstrap::install_build_artifact version=8.15.0 --targets localhost --run-as root

  test-install-build-artifact-task-on-other-os-via-containers:
    strategy:
      matrix:
        image:
          - almalinux:8
          - almalinux:9
          - rockylinux:8
          - rockylinux:9
          - debian:11
          - debian:12
          - fedora:42
          # Need to pull in the repo GPG keys for sles
          #          - registry.suse.com/suse/sle15:15.6
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: openvox_bootstrap
      - id: prep
        uses: ./openvox_bootstrap/.github/actions/container_task_prep
      - name: Run openvox-agent install task manually
        env:
          PT__installdir: ${{ github.workspace }}
          PT_version: "8.15.0"
        run: ./openvox_bootstrap/tasks/install_build_artifact_linux.sh
      - name: Verify openvox-agent is installed
        shell: bash
        env:
          PT__installdir: ${{ github.workspace }}
          PT_version: "8.15.0"
        run: ./openvox_bootstrap/tasks/check_linux.sh
      - name: Verify idempotency
        env:
          PT__installdir: ${{ github.workspace }}
          PT_version: "8.15.0"
        run: ./openvox_bootstrap/tasks/install_build_artifact_linux.sh

  test-install-build-artifact-task-noarch:
    strategy:
      matrix:
        package:
          - name: openvox-server
            version: 8.8.0
          - name: openvoxdb
            version: 8.9.0
          - name: openvoxdb-termini
            version: 8.9.0
        details:
          - image: almalinux:9
          - image: debian:12
          - image: ubuntu:24.04
    runs-on: ubuntu-latest
    container: ${{ matrix.details.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: openvox_bootstrap
      - id: prep
        uses: ./openvox_bootstrap/.github/actions/container_task_prep
      - name: Run openvox-agent install task manually
        env:
          PT__installdir: ${{ github.workspace }}
          PT_version: "8.19.1"
        run: ./openvox_bootstrap/tasks/install_build_artifact_linux.sh
      - name: Test noarch package installation
        env:
          PT__installdir: ${{ github.workspace }}
          PT_package: ${{ matrix.package.name }}
          PT_version: ${{ matrix.package.version }}
        run: ./openvox_bootstrap/tasks/install_build_artifact_linux.sh
      - name: Verify openvox server component  is installed
        shell: bash
        env:
          PACKAGE: ${{ matrix.package.name }}
          VERSION: ${{ matrix.package.version }}
        run: |-
          /opt/puppetlabs/bin/puppet resource package "${PACKAGE}" > openvox-package.status
          cat openvox-package.status
          grep "ensure.*=>.*'${VERSION}" openvox-package.status

  test-downgrade:
    strategy:
      matrix:
        image:
          - almalinux:8
          - almalinux:9
          - almalinux:10
          - rockylinux:8
          - rockylinux:9
          - rockylinux/rockylinux:10
          - debian:11
          - debian:12
          - debian:13
          - fedora:43
          # Need to pull in the repo GPG keys for sles
          #          - registry.suse.com/suse/sle15:15.6
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: openvox_bootstrap
      - id: prep
        uses: ./openvox_bootstrap/.github/actions/container_task_prep
      - name: Run openvox-agent install task manually
        env:
          PT__installdir: ${{ github.workspace }}
          PT_version: "8.25.0"
        run: ./openvox_bootstrap/tasks/install_build_artifact_linux.sh
      - name: Verify openvox-agent is installed
        env:
          PT__installdir: ${{ github.workspace }}
          PT_version: "8.25.0"
        run: ./openvox_bootstrap/tasks/check_linux.sh
      - name: Install older version of agent
        env:
          PT__installdir: ${{ github.workspace }}
          PT_version: "8.18.0"
        run: ./openvox_bootstrap/tasks/install_build_artifact_linux.sh
      - name: Verify openvox-agent is downgraded
        env:
          PT__installdir: ${{ github.workspace }}
          PT_version: "8.18.0"
        run: ./openvox_bootstrap/tasks/check_linux.sh
